apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spotify-pi-display
  description: Raspberry Pi Spotify now-playing display
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: yditj/projects/apps/spotify-pi-display
  links:
    - url: https://github.com/gustav0thethird/spotify-pi-display
      title: GitHub
      icon: github
  tags:
    - python
    - raspberrypi
    - spotify
    - hardware
    - apps
spec:
  type: service
  lifecycle: production
  owner: gtully
  system: apps
